services:
  backend:
    build:
      context: .           # root of repo with app.py & Dockerfile
      dockerfile: Dockerfile
    container_name: waba-backend
    ports:
      - "8000:8000"        # map host:container port
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
      # - ./src:/app/src
    command: ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - ./.env
  frontend:
    build:
      context: ./FrontendDavis   # your Vue project folder
      dockerfile: Dockerfile
    container_name: waba-frontend
    ports:
      - "5173:5173"         # Vite’s default dev port
    volumes:
      - ./FrontendDavis:/app     # mount source for HMR
      - /app/node_modules        # persist container’s node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"   # file‑watch polling in Docker
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]  # start the Vite dev server


networks:
  default:
    name: waba-network
    driver: bridge